version: 0.1
phases:
  install:
    commands:
      - ls -a
      - pwd
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket tgdeployment
                                   --output-template-file outputSamTemplate.yaml
artifacts:
  type: zip
  files:
    - samTemplate.yaml
    - outputSamTemplate.yaml