AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Updates the dynamoDb tabel with messages
Resources:
  TheGodFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: ./
      Events:
        TheGodApi:
          Type: Api
          Properties:
            Path: /TheGod
            Method: GET